name: authenticator
adopt-info: authenticator
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  # for GtkApplication registration
  authenticator:
    interface: dbus
    bus: session
    name: com.belmoussaoui.Authenticator
  gnome-keyring-svc:
    interface: dbus
    bus: session
    name: org.freedesktop.secrets
layout:
  /usr/share/authenticator:
    symlink: $SNAP/usr/share/authenticator

apps:
  authenticator:
    extensions: [gnome]
    command: usr/bin/authenticator
    common-id: com.bilelmoussaoui.Authenticator
    desktop: usr/share/applications/com.belmoussaoui.Authenticator.desktop
    plugs:
      - home
      - removable-media
      - network
      - password-manager-service

parts:
  zbar:
    source: https://git.linuxtv.org/zbar.git
    source-depth: 1
    #source-branch: stable-0.21
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-qt
      - --without-gtk
      - --without-xv
      - --without-imagemagick
      - --disable-video
      - --without-java
      - --with-python2=no
      - --enable-codes=qrcode
 
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'

  authenticator:
    after: [rustup, zbar]
    source: https://gitlab.gnome.org/World/Authenticator.git
    source-tag: '4.2.0'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    parse-info: [usr/share/metainfo/com.belmoussaoui.Authenticator.metainfo.xml]
    organize:
      snap/authenticator/current: .
    build-packages:
      - clang
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libpipewire-0.3-dev
      - libssl-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10)

  libraries:
    after: [ authenticator ]
    plugin: nil
    stage-packages:
      - libpipewire-0.3-0
    prime:
      - usr/lib/*/libpipewire-0.3.so.*

